# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.5.0-20221017
    container_name: selenium-hub
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
  chrome:
    image: selenium/node-chrome:4.5.0-20221017
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20221104
    volumes:
      - /tmp/videos:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4
  maven:
    image: maven:3.6.3-openjdk-11
    volumes:
      - ./:/tmp/automation_test
      - /var/tmp/:/var/tmp/
      - ~/.m2:/root/.m2
    working_dir: /tmp/automation_test
    depends_on:
      - selenium-hub
      - chrome
    command: >
      sh -c
      "mvn clean test -Dcucumber.filter.tags=@test -Dsuite=grid.xml -Dcucumber.execution.dry-run=true"
#      "&& mvn allure:serve"
      